### ISSUE TITLE
Will this work with any Doorbell entity?

### ISSUE THREAD

**Issue by derekpurdy** [nickneos/Appdaemon-Ring-Doorbell-Automations#2]
I have a Unifi Doorbell, looking for a way to have it announce on Google Home devices. I was wondering if this would work with the device?

It appears as "Detected occupancy" / "Cleared (no occupancy detected)" for the doorbell chime I believe.

binary_sensor.doorbell_doorbell

**Comment by nickneos** [comment]
So in Home Assistant the unifi doorbell shows up as `binary_sensor.doorbell_doorbell` and it's state (if you check in developer options) is `on` when it's pressed? If so yes I believe this should work 😃 

Let me know if it works and I'll update the readme

**Comment by derekpurdy** [comment]
State appears to be "Detected occupancy" / "Cleared (no occupancy detected)", i don't see On or Off anywhere. I'm pretty new to all this though.

**Comment by derekpurdy** [comment]
Also, while I got you here. 

I can't quite figure out how to use this. I see I need to drop the configuration into apps.yaml. I am running HA with HACS in a docker on Unraid, I'm not using HASS.IO. I have been trying on and off all day to both get this working in some way and also try to figure out how to enable logging for appdaemon, I can't find any output (logging) at all anywhere.

**Comment by derekpurdy** [comment]
Ok, so using built-in automation in HA, I was able to get the Doorbell to flip on a light when triggered.. So this SHOULD work, It was On/Off as you mentioned.. But unfortunately I still can't get appdaemon to work properly.

Thanks

**Comment by nickneos** [comment]
Yep it should work in that case with this app.

To install appdaemon on docker check out this link 
https://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html

**Comment by derekpurdy** [comment]
Hey @nickneos wow.. I was brainless.. I didn't realize appdaemon needed another docker to run! lol

anyways, I got it working.. lights up, the nest hub makes noise.,.. but just the connection sound, not the requested tts message.
